services:
  db:
    image: postgres:15
    env_file:
      - ../.env.production
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    env_file:
      - ../.env.production
    depends_on:
      - db
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      retries: 3
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    restart: always

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d/default.local.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  db_data:
  static_volume:
  media_volume:
