version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mi_db               # constante no sensible
      POSTGRES_USER: postgres          # constante no sensible
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # secreto inyectado por CI/CD
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ghcr.io/daviddlv007/infra/backend:latest
    environment:
      DJANGO_PROJECT: mi_proyecto
      DJANGO_APP: mi_app
      DJANGO_SETTINGS_MODULE: mi_proyecto.settings.production
      DJANGO_ALLOWED_HOSTS: softwaredlv.duckdns.org
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}   # secreto
      DATABASE_URL: ${DATABASE_URL}             # secreto
    depends_on:
      - db
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      retries: 3
    restart: always

  frontend:
    image: ghcr.io/daviddlv007/infra/frontend:latest
    restart: always
    # NOTA: se mantiene frontend aunque proxy sirva static

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d_active:/etc/nginx/conf.d:ro
      - static_volume:/var/www/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/ssl-params.conf:/etc/nginx/ssl-params.conf:ro
      - ./nginx/letsencrypt:/var/www/letsencrypt:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}  # secreto
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/letsencrypt:/var/www/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
       while :; do
         certbot renew --webroot -w /var/www/letsencrypt --deploy-hook 'nginx -s reload';
         sleep 12h & wait $${!};
       done"
    restart: always

volumes:
  db_data:
    name: db_data
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume
